### ISSUE TITLE
Support for YAML

### ISSUE THREAD

**Issue by cf-sewe** [znck/grammarly#208]
Thank you for your nice vscode addon! I am creating documentation out of YAML, and would be happy if the addon can directly check the spelling with Grammarly in YAML files.

For example I have this structure:

```yaml
something:
- name: some.property.key
  group: general
  summary: Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
  description: |
    Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet,
    consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
    Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. 

    Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis. 
  type: boolean
  default: true
  from: 5.5
- name: some.other.key
  ...
```

I think this could be quite generic, yaml value which looks like text could be checked with Grammarly?
